### ISSUE TITLE
!di only adds one character

### ISSUE THREAD

**Issue by p1x13st1ck** [alessio29/savagebot#102]
I've been trying to get a solid initiative down and add multiple characters, but I can only add one at a time

For instance, entering: _!di test1 test2 test3_  I get the following result:
```
 ========== Round 1 ========== 
NAME [MODS]          TOKENS  STATES  CARD  ALL CARDS                     
test1 []             [0]             7 ♥   [7 ♥]

```
The error doesn't give me much either:
Error while executing command !di. Details: null

I can still continue to add characters by doing a !di for each person, but that gets to be a little tediuos

**edit, I get the same thing when I use _!rm_ as well, I need to remove each individually and cannot remove multiple characters

**Comment by alessio29** [comment]
Fixed

**Comment by Joonasm** [comment]
![2020-03-29_16-38-02](https://user-images.githubusercontent.com/62698555/77850506-b5cb5680-71db-11ea-847b-b9e8812a5279.jpg)
This is still happening to me
